### ISSUE TITLE
same beacon as on Altbeacon.org?

### ISSUE THREAD

**Issue by ramsestom** [CharruaLab/AltBeacon#10]
Is this altbeacon library related to albeacon.org or is it something completely different? Because the specifications on altbeacon.org do not seems to use the system of 2 UUID (the generic one and the specific one) so it is a bit confusing. 
I am searching for a beacon system that could be used both on ios and android (and that would work even when application is in background) but on altbeacon.org, I could only find an API for android whereas this library is designed for IOS. So if the two use the same altbeacon specifications, I could definitely use these libs with the altbeacon beacons system; but it do not seems to be the case. Could you please clarify this?

**Comment by marpal** [comment]
Hi,
We are not related. They just used the same name than us (we were before ...)
