### ISSUE TITLE
Manufacturing Data in foreground vs background

### ISSUE THREAD

**Issue by johnnyman727** [CharruaLab/AltBeacon#9]
Hi,

I've been using the Node.js Noble library and the Tessel BLE module to inspect the advertising packets of the Altbeacon app when it is in the foreground and the background. I've noticed that the `manufacturingData` is `undefined` when the app is in the foreground but it's `<Buffer 4c 00 01 00 00 00 00 00 00 00 00 00 00 00 00 02 00 00 00>` when the app is in the background. Why is this?

**Comment by rahuldhodapkar** [comment]
I have also encountered this issue

**Comment by marpal** [comment]
This for the AltBeacon of radius.

**Comment by johnnyman727** [comment]
> This for the AltBeacon of radius.

@marpal can you explain a bit further what you mean?

**Comment by marpal** [comment]
@johnnyman727 you are talking http://altbeacon.org/ from Radius Networks. They have the same name than us (we were before) but is different stuff

**Comment by johnnyman727** [comment]
Ah gotcha. Sorry for the confusion.
